apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lhwdev-practice

resources:
- ../../base
- namespace.yaml
images:
- name: lhwdev/k8s-website-test
  newTag: 5bd47bdc23f103c5016a3e335890437c6eef0db7
