apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: lhwdev-practice
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: scg@scg.skku.ac.kr
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
