name: Build Docker Image
on:
  push:
    branches: [ main ]

env:
  dockerimage_name: lhwdev/k8s-website-test
  dockerimage_tag: ${{ github.sha }}
  config_branch: k8s-config
  mode: prod

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo
      
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.dockerimage_name }}
          tags: |
            ${{ env.dockerimage_tag }}
            latest
          flavor: "latest=true"
      
      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      
      - name: Pnpm Install
        run: |
          pnpm install
      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lhwdev
          password: ${{ secrets.docker_hub_token }}
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: repo
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
      
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.0.0

      - name: Checkout for Operation repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.config_branch }}
          path: config

      - name: Update Kubernetes resources
        run: |
          cd config/overlays/${{ env.mode }}/
          kustomize edit set image ${{ env.dockerimage_name }}:${{ env.dockerimage_tag }}
          cat kustomization.yaml

      - name: Commit manifest files
        run: |
          cd config
          git config --global user.email "lhwdev6@outlook.com"
          git config --global user.name "lhwdev"
          git commit -am "fix(infra): container image tag updated"
          git push -u origin ${{ env.config_branch }}

